apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.115
    path: /data/nfs/kafka

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-logs
  namespace: mq
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
