apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: mq
  labels:
    name: kafka
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
