apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: mq
  labels:
    name: zookeeper
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: zookeeper
